---
# Admins
- name: Create Admins group
  group:
    name: admins
    system: yes
    state: present

- name: Add Admins to Sudoers
  lineinfile:
    path: /etc/sudoers.d/10_admins
    line: '%admins ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

# User accounts
- name: Create group
  group:
    name: "{{ item.name }}"
  when: accounts is defined
  with_items: "{{ accounts }}"

- name: Create user
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.group | item.name }}"
    groups: "{{ item.groups | default(omit) }}"
    append: "{{ item.append | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
  when: accounts is defined
  with_items: "{{ accounts }}"

# SSH authorized keys
- name: Add authorized keys
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  when: accounts is defined
  with_subelements:
    - "{{ accounts }}"
    - authorized_keys
    - skip_missing: yes
