---
# Apt repositories
- name: Ensure Ubuntu universe repo is enabled ({{ ansible_distribution_version }} >= 16.04)
  apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release|lower }} universe"
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 16

- name: Ensure GnuPG package is installed
  package:
    name: gnupg2

- name: Add extra APT repositories
  apt_repository:
    repo: "{{ item.repo }}"
  with_items: "{{ apt_repositories }}"
  when: ansible_distribution == 'Ubuntu' and apt_repositories is defined
