---
# Add extra CA Certificates
- name: Install ca-certificates package (Debian/Ubuntu)
  apt:
    name: ca-certificates
    state: present
  when: ansible_os_family == "Debian"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install ca-certificates package (RedHat/CentOS)
  yum:
    name: ca-certificates
    state: present
  when: ansible_os_family == "RedHat"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Ensure local certs directory exists
  file:
    state: directory
    path: "{{ ca_path[ansible_os_family] }}/"

- name: Install CA Certificates
  copy:
    src: "{{ item }}"
    dest: "{{ ca_path[ansible_os_family] }}/"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - ca/*
  notify:
    - Update trusted CA certificates (Debian/Ubuntu)
    - Update trusted CA certificates (RedHat/CentOS < 7)
    - Update trusted CA certificates (RedHat/CentOS >= 7)
