---
- name: Provision DNS records
  cloudflare_dns:
    state: "{{ item.state | default('present') }}"
    zone: "{{ item.zone }}"
    type: "{{ item.type }}"
    record: "{{ item.record }}"
    value: "{{ item.value }}"
    proxied: "{{ item.proxied | default(omit) }}"
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
  with_items: "{{ cloudflare_dns_records }}"
  delegate_to: localhost
  run_once: yes
