---
- name: Ensure RSysLog Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rsyslog
    - rsyslog-gnutls

- name: Configure RSysLog
  template:
    src: "etc/rsyslog.d/{{ remote_logs_server }}.conf.j2"
    dest: "/etc/rsyslog.d/00_{{ remote_logs_server }}.conf"
  notify:
    - Restart RSysLog
