---
- name: Include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: vars

- import_tasks: apt.yml
  when: ansible_os_family == "Debian"

- import_tasks: packages.yml
  when: additional_packages is defined and additional_packages

- import_tasks: accounts.yml
  when: >
    ( local_groups is defined and local_groups ) or
    ( local_users is defined and local_users )

- import_tasks: cron.yml
  when: cron_jobs is defined and cron_jobs

- import_tasks: mounts.yml
  when: mount_points is defined and mount_points

- import_tasks: ca.yml
  when: install_ca_certificates is defined and install_ca_certificates|bool

- import_tasks: logs.yml
  when: remote_logs_enabled is defined and remote_logs_enabled|bool

- import_tasks: misc.yml
