---
- import_tasks: accounts.yml

- import_tasks: apt.yml
  when: >
    ansible_distribution == 'Ubuntu' and
    apt_repositories is defined and
    apt_repositories

- import_tasks: packages.yml
  when: additional_packages is defined and additional_packages

- import_tasks: pip.yml
  when: >
    ( pip_install_packages is defined and pip_install_packages ) or
    ( pip_user_install_packages is defined and pip_user_install_packages )

- import_tasks: ca.yml
  when: install_ca_certificates is defined and install_ca_certificates|bool

- import_tasks: cron.yml
  when: cron_jobs is defined and cron_jobs

- import_tasks: mounts.yml
  when: mount_points is defined and mount_points

- import_tasks: misc.yml
