---
- name: Include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: vars

# Common tasks
- import_tasks: apt.yml

# Software
- name: Install essential software (Debian/Ubuntu)
  apt:
    name: "{{ debian_software }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian" and debian_software is defined
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install essential software (RedHat/CentOS)
  yum:
    name: "{{ redhat_software }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat" and redhat_software is defined
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- import_tasks: accounts.yml
- import_tasks: ca.yml
- import_tasks: misc.yml

- import_tasks: logs.yml
  when: remote_logs_enabled

- import_tasks: msmtp.yml
  when: msmtp_enabled
