---
- name: Include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: vars

# Common tasks
- import_tasks: apt.yml
  when: ansible_os_family == "Debian"

# Software
- name: Install additional packages (Debian/Ubuntu)
  apt:
    name: "{{ debian_software }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian" and debian_software is defined and debian_software
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: Install additional packages (RedHat/CentOS)
  yum:
    name: "{{ redhat_software }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat" and redhat_software is defined and redhat_software
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- import_tasks: accounts.yml
  when: accounts is defined and accounts

- import_tasks: cron.yml
  when: cron_jobs is defined and cron_jobs

- import_tasks: mounts.yml
  when: mount_points is defined and mount_points

- import_tasks: ca.yml
  when: install_ca_certificates is defined and install_ca_certificates|bool

- import_tasks: logs.yml
  when: remote_logs_enabled is defined and remote_logs_enabled|bool

- import_tasks: msmtp.yml
  when: msmtp_enabled is defined and msmtp_enabled|bool and not ( ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 8 )

- import_tasks: misc.yml
