---
# Miscelanous
- name: Check if logind.conf exists
  stat:
    path: /etc/systemd/logind.conf
  register: systemd_logind_conf
- name: Disable lid switch
  lineinfile:
    dest: /etc/systemd/logind.conf
    regexp: HandleLidSwitch
    line: 'HandleLidSwitch=lock'
  notify: Restart LoginD
  when: disable_lid_switch|bool and systemd_logind_conf.stat.exists
