---
# Make sure the NFS package is installed if any mount point is of 'nfs' type
- name: Ensure NFS package is installed
  package:
    name: "{{ nfs_client_package_name }}"
  when: item.fstype is defined and item.fstype is match('nfs')
  with_items: "{{ mount_points }}"

# Make sure the RPCBind service is enabled and running if any mount point is of 'nfs' type
- name: Ensure RPCBind service is enabled and running
  service:
    name: rpcbind
    state: started
    enabled: yes
  when: item.fstype is defined and item.fstype is match('nfs')
  with_items: "{{ mount_points }}"

- name: Create the local directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
  with_items: "{{ mount_points }}"

- name: Create mount points
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    opts: "{{ item.opts | default(omit) }}"
    fstype: "{{ item.fstype | default(omit) }}"
    dump: "{{ item.dump | default(omit) }}"
    passno: "{{ item.passno | default(omit) }}"
    state: "{{ item.state | default('mounted') }}"
  with_items: "{{ mount_points }}"
