---
- name: Mount Points
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state }}"
    fstype: "{{ item.fstype }}"
  with_items: "{{ mount_points }}"
