---
- name: Install additional packages (Debian/Ubuntu)
  apt:
    name: "{{ additional_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: Install additional packages (RedHat/CentOS)
  yum:
    name: "{{ additional_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
