---
- name: Install additional packages (Debian/Ubuntu)
  apt:
    name: "{{ additional_packages }}"
    state: present
    update_cache: yes
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
