---
# Services
- name: Restart SSH Daemon
  service:
    name: sshd
    state: restarted
  ignore_errors: "{{ ansible_virtualization_type in [\"docker\", \"VirtualPC\"] }}"

- name: Restart LoginD
  service:
    name: systemd-logind
    state: restarted
  ignore_errors: "{{ ansible_virtualization_type in [\"docker\", \"VirtualPC\"] }}"

- name: Restart RSysLog
  service:
    name: rsyslog
    state: restarted
  ignore_errors: "{{ ansible_virtualization_type in [\"docker\", \"VirtualPC\"] }}"

# CA Certificates
- name: Update trusted CA certificates
  command: /usr/sbin/update-ca-certificates --fresh
