---
- name: Restart SSH Daemon
  service:
    name: sshd
    state: restarted

- name: Update trusted CA certificates Debian
  command: /usr/sbin/update-ca-certificates --fresh
  when: ansible_os_family == "Debian"
