---
# Services
- name: Restart SSH Daemon
  service:
    name: sshd
    state: restarted
- name: Restart LoginD
  service:
    name: systemd-logind
    state: restarted
- name: Restart RSysLog
  service:
    name: rsyslog
    state: restarted

# CA Certificates
- name: Update trusted CA certificates (Debian/Ubuntu)
  command: /usr/sbin/update-ca-certificates --fresh
  when: ansible_os_family == "Debian"

- name: Update trusted CA certificates (RedHat/CentOS < 7)
  command: /usr/bin/update-ca-trust enable
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 7

- name: Update trusted CA certificates (RedHat/CentOS >= 7)
  command: /usr/bin/update-ca-trust
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
