---
- name: Restart SSH Daemon
  service:
    name: sshd
    state: restarted
  ignore_errors: "{{ ansible_virtualization_type in [\"docker\", \"VirtualPC\"] }}"

- name: Restart LoginD
  service:
    name: systemd-logind
    state: restarted
  ignore_errors: "{{ ansible_virtualization_type in [\"docker\", \"VirtualPC\"] }}"

- name: Update trusted CA certificates
  command: /usr/sbin/update-ca-certificates --fresh

- name: Enable and start SystemD mount
  ansible.builtin.systemd:
    name: "{{ item.where[1:] | replace('/', '-') }}.mount"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items: "{{ systemd_mounts }}"
  when: not item.automount|default(no)

- name: Enable and start SystemD auto mount
  ansible.builtin.systemd:
    name: "{{ item.where[1:] | replace('/', '-') }}.automount"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items: "{{ systemd_mounts }}"
  when: item.automount|default(no)
