---
- name: Converge
  hosts: all
  become: yes
  vars:
    local_groups:
      - name: admins
        system: yes
        sudo: yes
    local_users:
      - name: test
        comment: Testing User
        groups: admins
        append: yes
        authorized_keys:
          - ssh-ed25519 AAAA testing
    additional_packages:
      - rolldice
    apt_repositories:
      - name: GIT
        repo: ppa:git-core/ppa
    pip_install_packages: [pip-install-test]
    pip_user_install_packages:
      - user: test
        packages: [colorama]
        state: latest
    cron_jobs:
      - name: Testing
        minute: '0'
        job: ls -lah > /dev/null
    mount_points:
      - name: Test
        path: /tmp/boot
        src: /boot
        opts: bind
        fstype: none
    install_ca_certificates: true
    disable_lid_switch: true
  tasks:
    - name: Include role
      include_role:
        name: vladgh.common
