---
- name: Converge
  hosts: all
  vars:
    install_ca_certificates: true
    remote_logs_enabled: true
    disable_lid_switch: true
    local_groups:
      - name: test
        sudo: yes
    local_users:
      - name: test
        comment: Testing User
        authorized_keys:
          - ssh-ed25519 AAAA testing
    additional_packages:
      - curl
    apt_repositories:
      - name: GIT
        repo: ppa:git-core/ppa
    cron_jobs:
      - name: Testing
        minute: '0'
        job: ls -lah > /dev/null
  tasks:
    - name: Include role
      include_role:
        name: vladgh.common
