---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-ubuntu:latest}"
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
