---
- name: Converge
  hosts: all
  vars:
    remote_logs_enabled: true
    msmtp_enabled: true
    disable_lid_switch: true
    accounts:
      - name: test
        comment: Testing Account
        authorized_keys:
          - ssh-ed25519 AAAA testing
    debian_software:
      - gnupg
    redhat_software:
      - gnupg
    apt_repositories:
      - name: GIT
        repo: ppa:git-core/ppa
  roles:
    - role: vladgh.common
