---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2

  roles:
    - role: vladgh.common
