---
- name: Converge
  hosts: all
  vars:
    remote_logs_enabled: true
    msmtp_enabled: true
    disable_lid_switch: true
    accounts:
      - name: test
        comment: Testing Account
        authorized_keys:
          - ssh-ed25519 AAAA testing
  roles:
    - role: vladgh.common
