---
- name: Converge
  hosts: all
  vars:
    remote_logs_enabled: true
    msmtp_enabled: true
    disable_lid_switch: true
    accounts:
      - name: test
        comment: Testing Account
        authorized_keys:
          - ssh-ed25519 AAAA testing
    debian_software:
      - curl
    redhat_software:
      - curl
    apt_repositories:
      - name: GIT
        repo: ppa:git-core/ppa
    cron_jobs:
      - name: Testing
        minute: '0'
        job: ls -alh > /dev/null
  roles:
    - role: vladgh.common
