name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MOLECULE_DISTRO: ${{ matrix.distro }}
    strategy:
      matrix:
        distro:
          - ubuntu1604
          - ubuntu1804
          - debian9
          - debian10
          - centos7
          - centos8
    steps:
    - uses: actions/checkout@v2
      with:
        path: vladgh.common
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip install --upgrade pip ansible molecule docker testinfra flake8 paramiko
    - name: Test
      run: cd vladgh.common && molecule test
