name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      ANSIBLE_ROLE_NAME: vladgh.common
    strategy:
      matrix:
        os:
          - ubuntu2004
          - ubuntu1804
          - debian10
          - debian9
    defaults:
      run:
        working-directory: ${{ env.ANSIBLE_ROLE_NAME }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ${{ env.ANSIBLE_ROLE_NAME }}
    - run: echo ${{ toJSON(github) }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: python3 -m pip install docker ansible ansible-lint yamllint molecule molecule-docker
    - name: Test role
      run: molecule test
      env:
        PY_COLORS: 1
        ANSIBLE_FORCE_COLOR: 1
        MOLECULE_DISTRO: ${{ matrix.os }}
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: python3 -m pip install ansible-base
    - name: Deploy
      run: ansible-galaxy role import --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} ${{ github.repository_owner }} ${{ github.repository }}

