name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: vladgh.common
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip install --upgrade pip ansible molecule docker testinfra flake8
    - run: ls -lah ./
    - run: ls -lah ./vladgh.common
    - name: Test
      run: molecule test
