name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MOLECULE_DISTRO: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu:16.04
          - ubuntu:18.04
          - debian:9
          - debian:10
          - centos:7
          - centos:8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip install molecule docker
    - name: Rename module folder
      run: cd ../ && mv ansible-role-common vladgh.common && cd vladgh.common
    - name: Test with Molecule
      run: molecule test
